NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
#   path('pages/', include('django.contrib.flatpages.urls')),
#   path('accounts/', include('django.contrib.auth.urls')),
   path("accounts/", include("allauth.urls")),
   path('news/', include('news.urls')),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import (
   PostList, PostDetail, PostSearchList, PostSearchDetail, PostCreate, PostUpdate, PostDelete, subscriptions,
   CategoryListView, subscribe
)
from django.views.decorators.cache import cache_page


urlpatterns = [
   #path('', cache_page(60)(PostList.as_view()), name='post_list'),
   path('<int:pk>', cache_page(300)(PostDetail.as_view()), name = 'post_detail'),
   path('search/', PostSearchList.as_view()),
   path('<int:pk>', PostSearchDetail.as_view()),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
 #  path('subscriptions/', subscriptions, name='subscriptions'),
   path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),

]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.validators import MinValueValidator


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, null=True, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

NewsPaper/news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post, Category, Author

class PostForm(forms.ModelForm):
    author = forms.ModelChoiceField(label='Автор', queryset=Author.objects.all(), empty_label=())
    title = forms.CharField(label='Заголовок')
    categoryType = forms.ChoiceField(label='Тип категории', choices=Post.CATEGORY_CHOICES)
    postCategory = forms.ModelMultipleChoiceField(label='Категория', queryset=Category.objects.all())

    class Meta:
        model = Post
        fields = [
            'author',
            'title',
            'categoryType',
            'text',
            "postCategory",
        ]

#    def clean(self):
#        cleaned_data = super().clean()
#        description = cleaned_data.get("description")
#        name = cleaned_data.get("name")

#        if name == description:
#            raise ValidationError(
#                "Описание не должно быть идентично названию."
#            )

#        return cleaned_data

NewsPaper/news/views.py
from datetime import datetime
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from .filters import PostFilter
from .forms import PostForm
from django.urls import reverse
#from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_protect
from .models import Subscription, Category
from django.core.cache import cache
from django.views.decorators.cache import cache_page
import logging

logger = logging.getLogger(__name__)


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscription.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscription.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscription.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )



class PostList(ListView):
    model = Post
    ordering = 'dateCreation'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['next post'] = None
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        return context


class PostSearchList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'search.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['next post'] = None
        context['filterset'] = self.filterset
        return context


class PostSearchDetail(DetailView):
    model = Post
    template_name = 'search.html'
    context_object_name = 'search'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        return context

# Добавляем новое представление для создания товаров.
class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_product',)
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.object.id})

class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_product',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_product',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')


class CategoryListView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(postCategory=self.category).order_by('-dateCreation')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context

@login_required()
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)

    message = 'Вы успешно подписались на категории'
    return render(request, 'subscribe.html', {'category': category, 'message': message})

NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load static %}
{% load custom_filters %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}
    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
   <h3>Всего: {{ news|length }} новостей</h3>

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

   <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}">Добавить новость</a>
    {% endif %}


   {% if category_news_list %}
       <table>
           <tr>
               <td><strong>Заголовок</strong></td>
               <td><strong>Дата публикации</strong></td>
               <td><strong>Статья</strong></td>


               {% if perms.news.change_post or perms.news.delete_post %}
               <td>Действия</td>
               {% endif %}

               <td><strong>Категория</strong></td>

           </tr>

           {% for new in category_news_list %}

           <tr>
               <td>{{ new.title }}</td>
               <td>{{ new.dateCreation|date:'d M Y' }}</td>
               <td>{{ new.text|truncatewords:20 }}</td>

               <td>
                   {% if perms.news.change_post %}
                   <a href="{% url 'post_update' pk=new.id %}">Изменить</a>
                   {% endif %}
                   {% if perms.news.delete_post %}
                   <a href="{% url 'post_delete' new.id %}">Удалить</a>
                   {% endif %}
               </td>
               <td>
               {% for category in new.postCategory.all %}
                    <a href="{% url 'category_list' category.id %}">{{ category }}</a>
               {% endfor %}
               </td>>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
  <h2>Здравствуйте! Новые статьи за неделю</h2>
  <ul>
    {% for post in posts %}
      <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>

</body>
</html>

NewsPaper/templates/new.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}


<hr>
   {% if new %}

               <h2 style="text-align: center;">{{ new.title|censor }}</h2>
               <p style="text-align: center;">Дата публикации: {{ new.dateCreation|date:'d M Y' }}</p>
<p>&nbsp;</p>
               <p style="text-align: center;">{{ new.text|censor }}</p>

           {% for new in news %}
           {% endfor %}
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
{% endblock content %}

NewsPaper/templates/news.html
{% extends 'flatpages/default.html' %}

{% load static %}
{% load custom_filters %}

{% block title %}
NEWS
{% endblock title %}

{% block content %}

   <h3>Всего: {{ news|length }} новостей</h3>

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

   <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}">Добавить новость</a>
    {% endif %}


   {% if news %}
       <table>
           <tr>

               <td><strong>Заголовок</strong></td>
               <td><strong>Дата публикации</strong></td>
               <td><strong>Статья</strong></td>


               {% if perms.news.change_post or perms.news.delete_post %}
               <td><strong>Действия</strong></td>
               {% endif %}

               <td><strong>Категория</strong></td>


           </tr>

           {% for new in news %}

           <tr>
               <td>{{ new.title }}</td>
               <td>{{ new.dateCreation|date:'d M Y' }}</td>
               <td>{{ new.text|truncatewords:20 }}</td>

               <td>
                   {% if perms.news.change_post %}
                   <a href="{% url 'post_update' pk=new.id %}">Изменить</a>
                   {% endif %}
                   {% if perms.news.delete_post %}
                   <a href="{% url 'post_delete' new.id %}">Удалить</a>
                   {% endif %}
               </td>
               <td>
               {% for category in new.postCategory.all %}
                    <a href="{% url 'category_list' category.id %}">{{ category }}</a>
               {% endfor %}

               </td>>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуй! Новая <a href="{{ link }}">статья</a> в твоем любимом разделе!</h2>
        <p>{{ text }}</p>
</body>
</html>

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Публикация</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load static %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Поиск публикаций
{% endblock title %}

{% block content %}

   <h1>Поиск публикаций</h1>
   <h3>{% current_time '%b %d %Y' %}</h3>
   <h6><i>Количество публикаций на текущей странице:{{ news|length }}</i></h6>
   <h6><i>Всего публикаций: {{ paginator.count }}</i></h6>

    <form action="" method="get">
        {{ filterset.form.non_field_errors }}
         {{ filterset.form.as_p }}
         <input type="submit" value="Найти" />
    </form>

   <hr>
   {% if news %}
       <table>
           <tr>
               <td><strong>Заголовок</strong></td>
               <td><strong>Статья</strong></td>
               <td><strong>Дата публикации</strong></td>
               <td><strong>Категория</strong></td>

           </tr>

           {% for post in news %}

           <tr>
               <td align="left">{{ post.title }}</td>
               <td align="left">{{ post.text|truncatewords:20 }}</td>
               <td>{{ post.dateCreation|date:'d M Y' }}</td>
               <td>{{ post.get_categoryType_display }}</td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}
{% block content %}
    <h1 class="text-center">{{ message }} {{  category }}</h1>
{% endblock %}

NewsPaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}